using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Text;
using System.IO;
using UnityEditor;

public class ItemGenerator
{
    public Texture2D spriteSheet1, spriteSheet2, spriteSheet3, spriteSheet4, spriteSheet5;

    Sprite[] sprites1, sprites2, sprites3, sprites4, sprites5;

    public Item[] itemsCommon1, itemsRare1, itemsLegendary1, itemsAncient1;
    public Item[] itemsCommon2, itemsRare2, itemsLegendary2, itemsAncient2;
    public Item[] itemsCommon3, itemsRare3, itemsLegendary3, itemsAncient3;
    public Item[] itemsCommon4, itemsRare4, itemsLegendary4, itemsAncient4;
    public Item[] itemsCommon5, itemsRare5, itemsLegendary5, itemsAncient5;

    private void Generate(Sprite[] sprites, string nameHolder){
        if(sprites == sprites4){
            for (int i = 0; i < sprites.Length - 1; i++){
                Item item1 = ScriptableObject.CreateInstance<Item>();
                Item item2 = ScriptableObject.CreateInstance<Item>();
                Item item3 = ScriptableObject.CreateInstance<Item>();
                Item item4 = ScriptableObject.CreateInstance<Item>();
                // Common cost set
                var cost = Random.Range(16, 301);
                var name = nameHolder + i;
                item1.id = name;
                item1.defaultCost = cost;
                item1.SetCommon();
                item1.sprite = sprites[i];
                AssetDatabase.CreateAsset(item1, "Assets/Resources/Item/AutoGenerated/Common/" + name + ".asset");

                item2.id = name;
                item2.defaultCost = cost;
                item2.SetRare();
                item2.sprite = sprites[i];
                AssetDatabase.CreateAsset(item2, "Assets/Resources/Item/AutoGenerated/Rare/" + name + ".asset");

                item3.id = name;
                item3.defaultCost = cost;
                item3.SetLegendray();
                item3.sprite = sprites[i];
                AssetDatabase.CreateAsset(item3, "Assets/Resources/Item/AutoGenerated/Legendary/" + name + ".asset");

                item4.id = name;
                item4.defaultCost = cost;
                item4.SetAncient();
                item4.sprite = sprites[i];
                AssetDatabase.CreateAsset(item4, "Assets/Resources/Item/AutoGenerated/Ancient/" + name + ".asset");
            }
        }
        else {
            for (int i = 0; i < sprites.Length; i++)
            {
                Item item1 = ScriptableObject.CreateInstance<Item>();
                Item item2 = ScriptableObject.CreateInstance<Item>();
                Item item3 = ScriptableObject.CreateInstance<Item>();
                Item item4 = ScriptableObject.CreateInstance<Item>();
                // Common cost set
                var cost = Random.Range(16, 301);
                var name = nameHolder + i;
                item1.id = name;
                item1.defaultCost = cost;
                item1.SetCommon();
                item1.sprite = sprites[i];
                AssetDatabase.CreateAsset(item1, "Assets/Resources/Item/AutoGenerated/Common/" + name + ".asset");

                item2.id = name;
                item2.defaultCost = cost;
                item2.SetRare();
                item2.sprite = sprites[i];
                AssetDatabase.CreateAsset(item2, "Assets/Resources/Item/AutoGenerated/Rare/" + name + ".asset");

                item3.id = name;
                item3.defaultCost = cost;
                item3.SetLegendray();
                item3.sprite = sprites[i];
                AssetDatabase.CreateAsset(item3, "Assets/Resources/Item/AutoGenerated/Legendary/" + name + ".asset");

                item4.id = name;
                item4.defaultCost = cost;
                item4.SetAncient();
                item4.sprite = sprites[i];
                AssetDatabase.CreateAsset(item4, "Assets/Resources/Item/AutoGenerated/Ancient/" + name + ".asset");
            }
        }
    }

    public void GenerateAll(){
        sprites1 = Resources.LoadAll<Sprite>("Image/Item/" + spriteSheet1.name);
        sprites2 = Resources.LoadAll<Sprite>("Image/Item/" + spriteSheet2.name);
        sprites3 = Resources.LoadAll<Sprite>("Image/Item/" + spriteSheet3.name);
        sprites4 = Resources.LoadAll<Sprite>("Image/Item/" + spriteSheet4.name);
        sprites5 = Resources.LoadAll<Sprite>("Image/Item/" + spriteSheet5.name);

        Generate(sprites1, spriteSheet1.name);
        Generate(sprites2, spriteSheet2.name);
        Generate(sprites3, spriteSheet3.name);
        Generate(sprites4, spriteSheet4.name);
        Generate(sprites5, spriteSheet5.name);
    }

    public void NameAssetsAll(){
        itemsCommon1 = Resources.LoadAll<Item>("Item/AutoGenerated/Common/01");
        itemsCommon2 = Resources.LoadAll<Item>("Item/AutoGenerated/Common/02");
        itemsCommon3 = Resources.LoadAll<Item>("Item/AutoGenerated/Common/03");
        itemsCommon4 = Resources.LoadAll<Item>("Item/AutoGenerated/Common/04");
        itemsCommon5 = Resources.LoadAll<Item>("Item/AutoGenerated/Common/05");

        itemsRare1 = Resources.LoadAll<Item>("Item/AutoGenerated/Rare/01");
        itemsRare2 = Resources.LoadAll<Item>("Item/AutoGenerated/Rare/02");
        itemsRare3 = Resources.LoadAll<Item>("Item/AutoGenerated/Rare/03");
        itemsRare4 = Resources.LoadAll<Item>("Item/AutoGenerated/Rare/04");
        itemsRare5 = Resources.LoadAll<Item>("Item/AutoGenerated/Rare/05");

        itemsLegendary1 = Resources.LoadAll<Item>("Item/AutoGenerated/Legendary/01");
        itemsLegendary2 = Resources.LoadAll<Item>("Item/AutoGenerated/Legendary/02");
        itemsLegendary3 = Resources.LoadAll<Item>("Item/AutoGenerated/Legendary/03");
        itemsLegendary4 = Resources.LoadAll<Item>("Item/AutoGenerated/Legendary/04");
        itemsLegendary5 = Resources.LoadAll<Item>("Item/AutoGenerated/Legendary/05");

        itemsAncient1 = Resources.LoadAll<Item>("Item/AutoGenerated/Ancient/01");
        itemsAncient2 = Resources.LoadAll<Item>("Item/AutoGenerated/Ancient/02");
        itemsAncient3 = Resources.LoadAll<Item>("Item/AutoGenerated/Ancient/03");
        itemsAncient4 = Resources.LoadAll<Item>("Item/AutoGenerated/Ancient/04");
        itemsAncient5 = Resources.LoadAll<Item>("Item/AutoGenerated/Ancient/05");

		NameAssetsEN();
        NameAssetsKR();
		NameAssetsJP();
        NameAssetsCN();
		NameAssetsCNT();
    }

   

    public void NameAssetsEN(){
        
        string filePath1 = Path.Combine(Application.streamingAssetsPath, "en01.json");
        string filePath2 = Path.Combine(Application.streamingAssetsPath, "en02.json");
        string filePath3 = Path.Combine(Application.streamingAssetsPath, "en03.json");
        string filePath4 = Path.Combine(Application.streamingAssetsPath, "en04.json");
        string filePath5 = Path.Combine(Application.streamingAssetsPath, "en05.json");

        if (File.Exists(filePath1) && File.Exists(filePath2) && File.Exists(filePath3) && File.Exists(filePath4) && File.Exists(filePath5))
        {
            string dataAsJson1 = File.ReadAllText(filePath1);
            string dataAsJson2 = File.ReadAllText(filePath2);
            string dataAsJson3 = File.ReadAllText(filePath3);
            string dataAsJson4 = File.ReadAllText(filePath4);
            string dataAsJson5 = File.ReadAllText(filePath5);

            LocalizationData loadedData1 = JsonUtility.FromJson<LocalizationData>(dataAsJson1);
            LocalizationData loadedData2 = JsonUtility.FromJson<LocalizationData>(dataAsJson2);
            LocalizationData loadedData3 = JsonUtility.FromJson<LocalizationData>(dataAsJson3);
            LocalizationData loadedData4 = JsonUtility.FromJson<LocalizationData>(dataAsJson4);
            LocalizationData loadedData5 = JsonUtility.FromJson<LocalizationData>(dataAsJson5);

            for (int i = 0; i < loadedData1.items.Length; i++)
            {
                itemsCommon1[i].enName = loadedData1.items[i].displayName;
                itemsCommon1[i].enDesc = loadedData1.items[i].displayDesc;
                itemsRare1[i].enName = loadedData1.items[i].displayName;
                itemsRare1[i].enDesc = loadedData1.items[i].displayDesc;
                itemsLegendary1[i].enName = loadedData1.items[i].displayName;
                itemsLegendary1[i].enDesc = loadedData1.items[i].displayDesc;
                itemsAncient1[i].enName = loadedData1.items[i].displayName;
                itemsAncient1[i].enDesc = loadedData1.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData2.items.Length; i++)
            {
                itemsCommon2[i].enName = loadedData2.items[i].displayName;
                itemsCommon2[i].enDesc = loadedData2.items[i].displayDesc;
                itemsRare2[i].enName = loadedData2.items[i].displayName;
                itemsRare2[i].enDesc = loadedData2.items[i].displayDesc;
                itemsLegendary2[i].enName = loadedData2.items[i].displayName;
                itemsLegendary2[i].enDesc = loadedData2.items[i].displayDesc;
                itemsAncient2[i].enName = loadedData2.items[i].displayName;
                itemsAncient2[i].enDesc = loadedData2.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData3.items.Length; i++)
            {
                itemsCommon3[i].enName = loadedData3.items[i].displayName;
                itemsCommon3[i].enDesc = loadedData3.items[i].displayDesc;
                itemsRare3[i].enName = loadedData3.items[i].displayName;
                itemsRare3[i].enDesc = loadedData3.items[i].displayDesc;
                itemsLegendary3[i].enName = loadedData3.items[i].displayName;
                itemsLegendary3[i].enDesc = loadedData3.items[i].displayDesc;
                itemsAncient3[i].enName = loadedData3.items[i].displayName;
                itemsAncient3[i].enDesc = loadedData3.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData4.items.Length; i++)
            {
                itemsCommon4[i].enName = loadedData4.items[i].displayName;
                itemsCommon4[i].enDesc = loadedData4.items[i].displayDesc;
                itemsRare4[i].enName = loadedData4.items[i].displayName;
                itemsRare4[i].enDesc = loadedData4.items[i].displayDesc;
                itemsLegendary4[i].enName = loadedData4.items[i].displayName;
                itemsLegendary4[i].enDesc = loadedData4.items[i].displayDesc;
                itemsAncient4[i].enName = loadedData4.items[i].displayName;
                itemsAncient4[i].enDesc = loadedData4.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData5.items.Length; i++)
            {
                itemsCommon5[i].enName = loadedData5.items[i].displayName;
                itemsCommon5[i].enDesc = loadedData5.items[i].displayDesc;
                itemsRare5[i].enName = loadedData5.items[i].displayName;
                itemsRare5[i].enDesc = loadedData5.items[i].displayDesc;
                itemsLegendary5[i].enName = loadedData5.items[i].displayName;
                itemsLegendary5[i].enDesc = loadedData5.items[i].displayDesc;
                itemsAncient5[i].enName = loadedData5.items[i].displayName;
                itemsAncient5[i].enDesc = loadedData5.items[i].displayDesc;
            }

        }
    }

    public void NameAssetsKR()
    {
        string filePath1 = Path.Combine(Application.streamingAssetsPath, "kr01.json");
        string filePath2 = Path.Combine(Application.streamingAssetsPath, "kr02.json");
        string filePath3 = Path.Combine(Application.streamingAssetsPath, "kr03.json");
        string filePath4 = Path.Combine(Application.streamingAssetsPath, "kr04.json");
        string filePath5 = Path.Combine(Application.streamingAssetsPath, "kr05.json");

        if (File.Exists(filePath1) && File.Exists(filePath2) && File.Exists(filePath3) && File.Exists(filePath4) && File.Exists(filePath5))
        {
            string dataAsJson1 = File.ReadAllText(filePath1);
            string dataAsJson2 = File.ReadAllText(filePath2);
            string dataAsJson3 = File.ReadAllText(filePath3);
            string dataAsJson4 = File.ReadAllText(filePath4);
            string dataAsJson5 = File.ReadAllText(filePath5);
            LocalizationData loadedData1 = JsonUtility.FromJson<LocalizationData>(dataAsJson1);
            LocalizationData loadedData2 = JsonUtility.FromJson<LocalizationData>(dataAsJson2);
            LocalizationData loadedData3 = JsonUtility.FromJson<LocalizationData>(dataAsJson3);
            LocalizationData loadedData4 = JsonUtility.FromJson<LocalizationData>(dataAsJson4);
            LocalizationData loadedData5 = JsonUtility.FromJson<LocalizationData>(dataAsJson5);

            for (int i = 0; i < loadedData1.items.Length; i++)
            {
                itemsCommon1[i].krName = loadedData1.items[i].displayName;
                itemsCommon1[i].krDesc = loadedData1.items[i].displayDesc;
                itemsRare1[i].krName = loadedData1.items[i].displayName;
                itemsRare1[i].krDesc = loadedData1.items[i].displayDesc;
                itemsLegendary1[i].krName = loadedData1.items[i].displayName;
                itemsLegendary1[i].krDesc = loadedData1.items[i].displayDesc;
                itemsAncient1[i].krName = loadedData1.items[i].displayName;
                itemsAncient1[i].krDesc = loadedData1.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData2.items.Length; i++)
            {
                itemsCommon2[i].krName = loadedData2.items[i].displayName;
                itemsCommon2[i].krDesc = loadedData2.items[i].displayDesc;
                itemsRare2[i].krName = loadedData2.items[i].displayName;
                itemsRare2[i].krDesc = loadedData2.items[i].displayDesc;
                itemsLegendary2[i].krName = loadedData2.items[i].displayName;
                itemsLegendary2[i].krDesc = loadedData2.items[i].displayDesc;
                itemsAncient2[i].krName = loadedData2.items[i].displayName;
                itemsAncient2[i].krDesc = loadedData2.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData3.items.Length; i++)
            {
                itemsCommon3[i].krName = loadedData3.items[i].displayName;
                itemsCommon3[i].krDesc = loadedData3.items[i].displayDesc;
                itemsRare3[i].krName = loadedData3.items[i].displayName;
                itemsRare3[i].krDesc = loadedData3.items[i].displayDesc;
                itemsLegendary3[i].krName = loadedData3.items[i].displayName;
                itemsLegendary3[i].krDesc = loadedData3.items[i].displayDesc;
                itemsAncient3[i].krName = loadedData3.items[i].displayName;
                itemsAncient3[i].krDesc = loadedData3.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData4.items.Length; i++)
            {
                itemsCommon4[i].krName = loadedData4.items[i].displayName;
                itemsCommon4[i].krDesc = loadedData4.items[i].displayDesc;
                itemsRare4[i].krName = loadedData4.items[i].displayName;
                itemsRare4[i].krDesc = loadedData4.items[i].displayDesc;
                itemsLegendary4[i].krName = loadedData4.items[i].displayName;
                itemsLegendary4[i].krDesc = loadedData4.items[i].displayDesc;
                itemsAncient4[i].krName = loadedData4.items[i].displayName;
                itemsAncient4[i].krDesc = loadedData4.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData5.items.Length; i++)
            {
                itemsCommon5[i].krName = loadedData5.items[i].displayName;
                itemsCommon5[i].krDesc = loadedData5.items[i].displayDesc;
                itemsRare5[i].krName = loadedData5.items[i].displayName;
                itemsRare5[i].krDesc = loadedData5.items[i].displayDesc;
                itemsLegendary5[i].krName = loadedData5.items[i].displayName;
                itemsLegendary5[i].krDesc = loadedData5.items[i].displayDesc;
                itemsAncient5[i].krName = loadedData5.items[i].displayName;
                itemsAncient5[i].krDesc = loadedData5.items[i].displayDesc;
            }

        }
    }
    public void NameAssetsCN()
    {
        string filePath1 = Path.Combine(Application.streamingAssetsPath, "cn01.json");
        string filePath2 = Path.Combine(Application.streamingAssetsPath, "cn02.json");
        string filePath3 = Path.Combine(Application.streamingAssetsPath, "cn03.json");
        string filePath4 = Path.Combine(Application.streamingAssetsPath, "cn04.json");
        string filePath5 = Path.Combine(Application.streamingAssetsPath, "cn05.json");

        if (File.Exists(filePath1) && File.Exists(filePath2) && File.Exists(filePath3) && File.Exists(filePath4) && File.Exists(filePath5))
        {
            string dataAsJson1 = File.ReadAllText(filePath1);
            string dataAsJson2 = File.ReadAllText(filePath2);
            string dataAsJson3 = File.ReadAllText(filePath3);
            string dataAsJson4 = File.ReadAllText(filePath4);
            string dataAsJson5 = File.ReadAllText(filePath5);
            LocalizationData loadedData1 = JsonUtility.FromJson<LocalizationData>(dataAsJson1);
            LocalizationData loadedData2 = JsonUtility.FromJson<LocalizationData>(dataAsJson2);
            LocalizationData loadedData3 = JsonUtility.FromJson<LocalizationData>(dataAsJson3);
            LocalizationData loadedData4 = JsonUtility.FromJson<LocalizationData>(dataAsJson4);
            LocalizationData loadedData5 = JsonUtility.FromJson<LocalizationData>(dataAsJson5);

            for (int i = 0; i < loadedData1.items.Length; i++)
            {
                itemsCommon1[i].cnName = loadedData1.items[i].displayName;
                itemsCommon1[i].cnDesc = loadedData1.items[i].displayDesc;
                itemsRare1[i].cnName = loadedData1.items[i].displayName;
                itemsRare1[i].cnDesc = loadedData1.items[i].displayDesc;
                itemsLegendary1[i].cnName = loadedData1.items[i].displayName;
                itemsLegendary1[i].cnDesc = loadedData1.items[i].displayDesc;
                itemsAncient1[i].cnName = loadedData1.items[i].displayName;
                itemsAncient1[i].cnDesc = loadedData1.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData2.items.Length; i++)
            {
                itemsCommon2[i].cnName = loadedData2.items[i].displayName;
                itemsCommon2[i].cnDesc = loadedData2.items[i].displayDesc;
                itemsRare2[i].cnName = loadedData2.items[i].displayName;
                itemsRare2[i].cnDesc = loadedData2.items[i].displayDesc;
                itemsLegendary2[i].cnName = loadedData2.items[i].displayName;
                itemsLegendary2[i].cnDesc = loadedData2.items[i].displayDesc;
                itemsAncient2[i].cnName = loadedData2.items[i].displayName;
                itemsAncient2[i].cnDesc = loadedData2.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData3.items.Length; i++)
            {
                itemsCommon3[i].cnName = loadedData3.items[i].displayName;
                itemsCommon3[i].cnDesc = loadedData3.items[i].displayDesc;
                itemsRare3[i].cnName = loadedData3.items[i].displayName;
                itemsRare3[i].cnDesc = loadedData3.items[i].displayDesc;
                itemsLegendary3[i].cnName = loadedData3.items[i].displayName;
                itemsLegendary3[i].cnDesc = loadedData3.items[i].displayDesc;
                itemsAncient3[i].cnName = loadedData3.items[i].displayName;
                itemsAncient3[i].cnDesc = loadedData3.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData4.items.Length; i++)
            {
                itemsCommon4[i].cnName = loadedData4.items[i].displayName;
                itemsCommon4[i].cnDesc = loadedData4.items[i].displayDesc;
                itemsRare4[i].cnName = loadedData4.items[i].displayName;
                itemsRare4[i].cnDesc = loadedData4.items[i].displayDesc;
                itemsLegendary4[i].cnName = loadedData4.items[i].displayName;
                itemsLegendary4[i].cnDesc = loadedData4.items[i].displayDesc;
                itemsAncient4[i].cnName = loadedData4.items[i].displayName;
                itemsAncient4[i].cnDesc = loadedData4.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData5.items.Length; i++)
            {
                itemsCommon5[i].cnName = loadedData5.items[i].displayName;
                itemsCommon5[i].cnDesc = loadedData5.items[i].displayDesc;
                itemsRare5[i].cnName = loadedData5.items[i].displayName;
                itemsRare5[i].cnDesc = loadedData5.items[i].displayDesc;
                itemsLegendary5[i].cnName = loadedData5.items[i].displayName;
                itemsLegendary5[i].cnDesc = loadedData5.items[i].displayDesc;
                itemsAncient5[i].cnName = loadedData5.items[i].displayName;
                itemsAncient5[i].cnDesc = loadedData5.items[i].displayDesc;
            }

        }
    }
    public void NameAssetsJP()
    {
        string filePath1 = Path.Combine(Application.streamingAssetsPath, "jp01.json");
        string filePath2 = Path.Combine(Application.streamingAssetsPath, "jp02.json");
        string filePath3 = Path.Combine(Application.streamingAssetsPath, "jp03.json");
        string filePath4 = Path.Combine(Application.streamingAssetsPath, "jp04.json");
        string filePath5 = Path.Combine(Application.streamingAssetsPath, "jp05.json");

        if (File.Exists(filePath1) && File.Exists(filePath2) && File.Exists(filePath3) && File.Exists(filePath4) && File.Exists(filePath5))
        {
            string dataAsJson1 = File.ReadAllText(filePath1);
            string dataAsJson2 = File.ReadAllText(filePath2);
            string dataAsJson3 = File.ReadAllText(filePath3);
            string dataAsJson4 = File.ReadAllText(filePath4);
            string dataAsJson5 = File.ReadAllText(filePath5);
            LocalizationData loadedData1 = JsonUtility.FromJson<LocalizationData>(dataAsJson1);
            LocalizationData loadedData2 = JsonUtility.FromJson<LocalizationData>(dataAsJson2);
            LocalizationData loadedData3 = JsonUtility.FromJson<LocalizationData>(dataAsJson3);
            LocalizationData loadedData4 = JsonUtility.FromJson<LocalizationData>(dataAsJson4);
            LocalizationData loadedData5 = JsonUtility.FromJson<LocalizationData>(dataAsJson5);

            for (int i = 0; i < loadedData1.items.Length; i++)
            {
                itemsCommon1[i].jpName = loadedData1.items[i].displayName;
                itemsCommon1[i].jpDesc = loadedData1.items[i].displayDesc;
                itemsRare1[i].jpName = loadedData1.items[i].displayName;
                itemsRare1[i].jpDesc = loadedData1.items[i].displayDesc;
                itemsLegendary1[i].jpName = loadedData1.items[i].displayName;
                itemsLegendary1[i].jpDesc = loadedData1.items[i].displayDesc;
                itemsAncient1[i].jpName = loadedData1.items[i].displayName;
                itemsAncient1[i].jpDesc = loadedData1.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData2.items.Length; i++)
            {
                itemsCommon2[i].jpName = loadedData2.items[i].displayName;
                itemsCommon2[i].jpDesc = loadedData2.items[i].displayDesc;
                itemsRare2[i].jpName = loadedData2.items[i].displayName;
                itemsRare2[i].jpDesc = loadedData2.items[i].displayDesc;
                itemsLegendary2[i].jpName = loadedData2.items[i].displayName;
                itemsLegendary2[i].jpDesc = loadedData2.items[i].displayDesc;
                itemsAncient2[i].jpName = loadedData2.items[i].displayName;
                itemsAncient2[i].jpDesc = loadedData2.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData3.items.Length; i++)
            {
                itemsCommon3[i].jpName = loadedData3.items[i].displayName;
                itemsCommon3[i].jpDesc = loadedData3.items[i].displayDesc;
                itemsRare3[i].jpName = loadedData3.items[i].displayName;
                itemsRare3[i].jpDesc = loadedData3.items[i].displayDesc;
                itemsLegendary3[i].jpName = loadedData3.items[i].displayName;
                itemsLegendary3[i].jpDesc = loadedData3.items[i].displayDesc;
                itemsAncient3[i].jpName = loadedData3.items[i].displayName;
                itemsAncient3[i].jpDesc = loadedData3.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData4.items.Length; i++)
            {
                itemsCommon4[i].jpName = loadedData4.items[i].displayName;
                itemsCommon4[i].jpDesc = loadedData4.items[i].displayDesc;
                itemsRare4[i].jpName = loadedData4.items[i].displayName;
                itemsRare4[i].jpDesc = loadedData4.items[i].displayDesc;
                itemsLegendary4[i].jpName = loadedData4.items[i].displayName;
                itemsLegendary4[i].jpDesc = loadedData4.items[i].displayDesc;
                itemsAncient4[i].jpName = loadedData4.items[i].displayName;
                itemsAncient4[i].jpDesc = loadedData4.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData5.items.Length; i++)
            {
                itemsCommon5[i].jpName = loadedData5.items[i].displayName;
                itemsCommon5[i].jpDesc = loadedData5.items[i].displayDesc;
                itemsRare5[i].jpName = loadedData5.items[i].displayName;
                itemsRare5[i].jpDesc = loadedData5.items[i].displayDesc;
                itemsLegendary5[i].jpName = loadedData5.items[i].displayName;
                itemsLegendary5[i].jpDesc = loadedData5.items[i].displayDesc;
                itemsAncient5[i].jpName = loadedData5.items[i].displayName;
                itemsAncient5[i].jpDesc = loadedData5.items[i].displayDesc;
            }

        }
    }
    public void NameAssetsCNT()
    {
        string filePath1 = Path.Combine(Application.streamingAssetsPath, "cnt01.json");
        string filePath2 = Path.Combine(Application.streamingAssetsPath, "cnt02.json");
        string filePath3 = Path.Combine(Application.streamingAssetsPath, "cnt03.json");
        string filePath4 = Path.Combine(Application.streamingAssetsPath, "cnt04.json");
        string filePath5 = Path.Combine(Application.streamingAssetsPath, "cnt05.json");

        if (File.Exists(filePath1) && File.Exists(filePath2) && File.Exists(filePath3) && File.Exists(filePath4) && File.Exists(filePath5))
        {
            string dataAsJson1 = File.ReadAllText(filePath1);
            string dataAsJson2 = File.ReadAllText(filePath2);
            string dataAsJson3 = File.ReadAllText(filePath3);
            string dataAsJson4 = File.ReadAllText(filePath4);
            string dataAsJson5 = File.ReadAllText(filePath5);
            LocalizationData loadedData1 = JsonUtility.FromJson<LocalizationData>(dataAsJson1);
            LocalizationData loadedData2 = JsonUtility.FromJson<LocalizationData>(dataAsJson2);
            LocalizationData loadedData3 = JsonUtility.FromJson<LocalizationData>(dataAsJson3);
            LocalizationData loadedData4 = JsonUtility.FromJson<LocalizationData>(dataAsJson4);
            LocalizationData loadedData5 = JsonUtility.FromJson<LocalizationData>(dataAsJson5);

            for (int i = 0; i < loadedData1.items.Length; i++)
            {
                itemsCommon1[i].cntName = loadedData1.items[i].displayName;
                itemsCommon1[i].cntDesc = loadedData1.items[i].displayDesc;
                itemsRare1[i].cntName = loadedData1.items[i].displayName;
                itemsRare1[i].cntDesc = loadedData1.items[i].displayDesc;
                itemsLegendary1[i].cntName = loadedData1.items[i].displayName;
                itemsLegendary1[i].cntDesc = loadedData1.items[i].displayDesc;
                itemsAncient1[i].cntName = loadedData1.items[i].displayName;
                itemsAncient1[i].cntDesc = loadedData1.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData2.items.Length; i++)
            {
                itemsCommon2[i].cntName = loadedData2.items[i].displayName;
                itemsCommon2[i].cntDesc = loadedData2.items[i].displayDesc;
                itemsRare2[i].cntName = loadedData2.items[i].displayName;
                itemsRare2[i].cntDesc = loadedData2.items[i].displayDesc;
                itemsLegendary2[i].cntName = loadedData2.items[i].displayName;
                itemsLegendary2[i].cntDesc = loadedData2.items[i].displayDesc;
                itemsAncient2[i].cntName = loadedData2.items[i].displayName;
                itemsAncient2[i].cntDesc = loadedData2.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData3.items.Length; i++)
            {
                itemsCommon3[i].cntName = loadedData3.items[i].displayName;
                itemsCommon3[i].cntDesc = loadedData3.items[i].displayDesc;
                itemsRare3[i].cntName = loadedData3.items[i].displayName;
                itemsRare3[i].cntDesc = loadedData3.items[i].displayDesc;
                itemsLegendary3[i].cntName = loadedData3.items[i].displayName;
                itemsLegendary3[i].cntDesc = loadedData3.items[i].displayDesc;
                itemsAncient3[i].cntName = loadedData3.items[i].displayName;
                itemsAncient3[i].cntDesc = loadedData3.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData4.items.Length; i++)
            {
                itemsCommon4[i].cntName = loadedData4.items[i].displayName;
                itemsCommon4[i].cntDesc = loadedData4.items[i].displayDesc;
                itemsRare4[i].cntName = loadedData4.items[i].displayName;
                itemsRare4[i].cntDesc = loadedData4.items[i].displayDesc;
                itemsLegendary4[i].cntName = loadedData4.items[i].displayName;
                itemsLegendary4[i].cntDesc = loadedData4.items[i].displayDesc;
                itemsAncient4[i].cntName = loadedData4.items[i].displayName;
                itemsAncient4[i].cntDesc = loadedData4.items[i].displayDesc;
            }

            for (int i = 0; i < loadedData5.items.Length; i++)
            {
                itemsCommon5[i].cntName = loadedData5.items[i].displayName;
                itemsCommon5[i].cntDesc = loadedData5.items[i].displayDesc;
                itemsRare5[i].cntName = loadedData5.items[i].displayName;
                itemsRare5[i].cntDesc = loadedData5.items[i].displayDesc;
                itemsLegendary5[i].cntName = loadedData5.items[i].displayName;
                itemsLegendary5[i].cntDesc = loadedData5.items[i].displayDesc;
                itemsAncient5[i].cntName = loadedData5.items[i].displayName;
                itemsAncient5[i].cntDesc = loadedData5.items[i].displayDesc;
            }

        }
    }
}

[System.Serializable]
public class LocalizationData
{
    public LocalizationItem[] items;
}

[System.Serializable]
public class LocalizationItem
{
    public string displayName;
    public string displayDesc;
}




